SELECT * FROM ['Data Sales Adidas$']
--checking for nulls
SELECT * FROM ['Data Sales Adidas$']
WHERE RETAILER IS NULL
--DELETING NULL VALUES
DELETE FROM ['Data Sales Adidas$']
WHERE RETAILER IS NULL

--CREATING A COLUMN INCLUDING THE YEAR OF THE TRANSACTION
ALTER TABLE ['Data Sales Adidas$'] ADD [YEAR] INT;
UPDATE ['Data Sales Adidas$']
SET [YEAR] = YEAR([INVOICE-DATE])

-- CHECKING DISTINCT VALUES OF THE YEARS
SELECT YEAR, COUNT( [YEAR]) FROM ['Data Sales Adidas$']
GROUP BY [YEAR]
--
--CHECKING DISTINCT VALUES OF THE STATES
SELECT DISTINCT STATE FROM['Data Sales Adidas$']
--CHECKING FOR RETAILERS
SELECT DISTINCT retailer FROM ['Data Sales Adidas$']
--CALCULATING TOTAL SALES PER RETAILER
SELECT RETAILER, SUM([total-sales]) AS SU FROM ['Data Sales Adidas$']
GROUP BY RETAILER
ORDER BY SU DESC
SELECT COUNT(RETAILER) FROM ['Data Sales Adidas$']
WHERE RETAILER LIKE 'Retailer'
DELETE FROM ['Data Sales Adidas$']
WHERE retailer LIKE 'Retailer'
-- calculating TOTAL PROFIT PER RETAILER
SELECT RETAILER, SUM([operatin-profit]) AS SU FROM ['Data Sales Adidas$']
GROUP BY RETAILER
ORDER BY SU DESC
--MOST SELLING METHOD SALES
SELECT [sales-method],SUM([total-sales]) AS SU, SUM([total-sales])*100 /SUM(SUM([total-sales])) OVER() AS P FROM ['Data Sales Adidas$']
GROUP BY [sales-method]
ORDER BY P DESC
-- MOST SELLING STATE
SELECT STATE, SUM([total-sales]) AS SU FROM ['Data Sales Adidas$']
GROUP BY STATE
ORDER BY SU DESC
-- MOST SELLING PRODUCT
SELECT PRODUCT, SUM([total-sales]) AS SU FROM ['Data Sales Adidas$']
GROUP BY PRODUCT
ORDER BY SU DESC